=== yrukan/XMLExample/resources/Family-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xns:schema xmlns:xns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/Family-schema" xmlns:itacby="http://www.it-academy.by/Family-schema"
	elementFormDefault="qualified">

	<xns:element name="families">
		<xns:complexType>
			<xns:sequence maxOccurs="unbounded">
				<xns:element name="family" type="itacby:family_type" />
			</xns:sequence>

		</xns:complexType>
	</xns:element>

	<xns:complexType name="family_member_info">
		<xns:sequence>
			<xns:element name="surname" type="xns:string" />
			<xns:element name="name" type="xns:string" />
			<xns:element name="age">
				<xns:simpleType>
					<xns:restriction base="xns:int">
						<xns:minExclusive value="0"></xns:minExclusive>
						<xns:maxExclusive value="200"></xns:maxExclusive>
					</xns:restriction>
				</xns:simpleType>
			</xns:element>
		</xns:sequence>
	</xns:complexType>

	<xns:complexType name="family_type">
		<xns:sequence>
			<xns:element name="mother" type="itacby:mother_type" />
			<xns:element name="father" type="itacby:father_type" />
			<xns:element name="children" type="itacby:children_type"
				minOccurs="0" />
		</xns:sequence>
		<xns:attribute name="id" />
	</xns:complexType>

	<xns:complexType name="mother_type">
		<xns:complexContent>
			<xns:extension base="itacby:family_member_info">
				<xns:sequence>
					<xns:element name="maiden-name" type="xns:string" />
				</xns:sequence>
			</xns:extension>
		</xns:complexContent>
	</xns:complexType>

	<xns:complexType name="father_type">
		<xns:sequence>
			<xns:element name="surname" type="xns:string" />
			<xns:element name="name" type="xns:string" />
			<xns:element name="age" type="xns:int" />
		</xns:sequence>
	</xns:complexType>

	<xns:complexType name="children_type">
		<xns:sequence maxOccurs="unbounded">
			<xns:element name="child" type="itacby:child_type"
				minOccurs="0" />
		</xns:sequence>
	</xns:complexType>

	<xns:complexType name="child_type">
		<xns:complexContent>
			<xns:extension base="itacby:family_member_info">
				<xns:choice>
					<xns:element name="male" />
					<xns:element name="female" />
				</xns:choice>
			</xns:extension>
		</xns:complexContent>
	</xns:complexType>
</xns:schema>

=== yrukan/XMLExample/resources/Family.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<families xmlns="http://www.it-academy.by/Family-schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.it-academy.by/Family-schema Family-schema.xsd">

	<family id="1">
		<mother>
			<surname>Ivanova</surname>
			<name>Anne</name>
			<age>35</age>
			<maiden-name>Petrova</maiden-name>
		</mother>
		<father>
			<surname>Ivanov</surname>
			<name>Igor</name>
			<age>25</age>
		</father>
		<children>
			<child>
				<surname>Ivanov</surname>
				<name>Ivan</name>
				<age>2</age>
				<male/>
			</child>
			<child>
				<surname>Ivanova</surname>
				<name>Kate</name>
				<age>3</age>
				<female/>
			</child>
		</children>
	</family>
	<family id="2">
		<mother>
			<surname>Ivanova</surname>
			<name>Anne</name>
			<age>35</age>
			<maiden-name>Petrova</maiden-name>
		</mother>
		<father>
			<surname>Ivanov</surname>
			<name>Igor</name>
			<age>25</age>
		</father>
		<children>
			
		</children>
	</family>
</families>
